### PR TITLE
Update This.Javascript 

### PR DESCRIPTION
**Pull request by jorgelainfiesta**
Updated featured event and add speakers to JS.Interactive
Added new events

### CODE REVIEW

**Comment by ladyleet** [comment]
Hello! @jorgelainfiesta I haven't reviewed been able to pull down the project yet because I'm at the airport, but I did notice that I never updated the mailchimp lists for subscription, which probably means you have not been able to add it correctly to the site.

Also, can you make sure the YouTube URLs for the livestreams reflect the correct event? It seemed like the Aug/Sept links linked to the incorrect ones.

Quick review! :) I won't be able to pull down the project until later tonight.

**Comment by jorgelainfiesta** [comment]
Hi @ladyleet, thanks for taking the time to review this. You were right about the Youtube and Mailchimp links. I updated the PR to add the correct links to the new events. Please check it back when you get a chance.

**Comment by taras** [comment]
@ladyleet is this good to go?

**Comment by ladyleet** [comment]
Didn't this get merged?

**Pull request merged**
