### PR TITLE
This Dot Javascript page and styles.

### PR DESCRIPTION
**Pull request by jorgelainfiesta**
Hi! This is the page for This.Javascript

image

### CODE REVIEW

**Comment by ladyleet** [comment]
@jorgelainfiesta this looks so good! :) can we just change This.JavaScript Interactive to be JS.Interactive pls in all references?

**Comment by ladyleet** [comment]
Cool! Is it on the site now / link?

Will the This.JavaScript links be linked to this now?

I think we should probably go through each link with a fine toothed comb
and make sure all links properly after all these launches! So good!

**Comment by jorgelainfiesta** [comment]
It's not up yet, but the route is `/javascript`. I also don't have yet from which places we should be linking to this page.

**Comment by ladyleet** [comment]
<3 Cool! Looking forward to it thanks for pushing this out this week. <3
Can't wait for next week! Enjoy your new year! <3

**Pull request merged**
